name: geo
channels:
  - conda-forge
dependencies:
  - gdal=3.2.2
  - pip
  - pip:
      - geopandas
      - streamlit
      - localtileserver
      - palettable
      - streamlit-folium
      - geemap==0.11.1
      # - git+git://github.com/giswqs/geemap
