name: geo
channels:
  - conda-forge
dependencies:
  - gdal=3.2.2
  - pip
  - pip:
      - geopandas
      - streamlit
      - streamlit-folium
      - git+git://github.com/giswqs/leafmap
      - git+git://github.com/giswqs/geemap
