name: geo_env
channels:
    - conda-forge
dependencies:
    - pip
    - gdal
    - localtileserver
    - ipyleaflet
    - pip:
        - geopandas=0.10.2
        - streamlit=1.5.0
        - pyparsing=2.4.2
        - folium=0.12.1
        - geemap=0.11.1
        - earthengine-api
        - Shapely=1.8.0
